// <auto-generated />
using System;
using EnlightEnglishCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnlightEnglishCenter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023131508_AddLoTrinhHocToTestDauVao")]
    partial class AddLoTrinhHocToTestDauVao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnlightEnglishCenter.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("LoaiBaoCao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiLap")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex(new[] { "NguoiLap" }, "IX_BaoCao_NguoiLap");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DangKyTuVan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DangKyTuVan");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemDanh", b =>
                {
                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<int?>("MaHocVienNavigationMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaLichNavigationMaLich")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHocVien", "MaLich");

                    b.HasIndex(new[] { "MaHocVienNavigationMaNguoiDung" }, "IX_DiemDanh_MaHocVienNavigationMaNguoiDung");

                    b.HasIndex(new[] { "MaLichNavigationMaLich" }, "IX_DiemDanh_MaLichNavigationMaLich");

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemSo", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDiem");

                    b.HasIndex(new[] { "MaHocVien" }, "IX_DiemSo_MaHocVien");

                    b.HasIndex(new[] { "MaLop" }, "IX_DiemSo_MaLop");

                    b.ToTable("DiemSo");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DkHocVienLopHoc", b =>
                {
                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHocVien", "MaLop");

                    b.HasIndex(new[] { "MaLop" }, "IX_DK_HocVien_LopHoc_MaLop");

                    b.ToTable("DK_HocVien_LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.GiaoVien", b =>
                {
                    b.Property<int>("MaGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoVien"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaGiaoVien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.HocPhi", b =>
                {
                    b.Property<int>("MaHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocPhi"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDongCuoi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienDaDong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SoTienPhaiDong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHocPhi");

                    b.HasIndex(new[] { "MaHocVien" }, "IX_HocPhi_MaHocVien");

                    b.HasIndex(new[] { "MaLop" }, "IX_HocPhi_MaLop");

                    b.ToTable("HocPhi");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHocVien");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("CapDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuanDauRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HocPhi")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("LoTrinhHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichHoc", b =>
                {
                    b.Property<int>("MaLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHoc"));

                    b.Property<string>("GioBatDau")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GioKetThuc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayHoc")
                        .HasColumnType("date");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaGiaoVien");

                    b.HasIndex("MaLop");

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichSuTruyCap", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChiIp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChiIP");

                    b.Property<string>("HanhDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex(new[] { "MaNguoiDung" }, "IX_LichSuTruyCap_MaNguoiDung");

                    b.ToTable("LichSuTruyCap", t =>
                        {
                            t.Property("DiaChiIP")
                                .HasColumnName("DiaChiIP1");
                        });
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichThi", b =>
                {
                    b.Property<int>("MaThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThi"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("GioThi")
                        .HasColumnType("time");

                    b.Property<string>("LoaiThi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayThi")
                        .HasColumnType("date");

                    b.HasKey("MaThi");

                    b.HasIndex(new[] { "MaLop" }, "IX_LichThi_MaLop");

                    b.ToTable("LichThi");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGiaoVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LuongGiaoVien", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal?>("LuongMoiBuoi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int?>("SoBuoiDay")
                        .HasColumnType("int");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(21, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLuong");

                    b.HasIndex(new[] { "MaGiaoVien" }, "IX_LuongGiaoVien_MaGiaoVien");

                    b.ToTable("LuongGiaoVien");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("KhoaDenNgay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("SoLanSaiMatKhau")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex(new[] { "MaVaiTro" }, "IX_NguoiDung_MaVaiTro");

                    b.HasIndex(new[] { "TenDangNhap" }, "IX_NguoiDung_TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NhanVienLeTan", b =>
                {
                    b.Property<int>("MaLeTan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLeTan"));

                    b.Property<string>("CaLam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KinhNghiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLeTan");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhanVienLeTan");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.PhanCongGiangDay", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaGiaoVien");

                    b.HasIndex("MaLop");

                    b.ToTable("PhanCongGiangDay");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.PhongDaoTao", b =>
                {
                    b.Property<int>("MaPhongDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongDaoTao"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhongDaoTao");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PhongDaoTao");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.PhongHoc", b =>
                {
                    b.Property<int>("MaPhongHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongHoc"));

                    b.Property<string>("TenPhong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhongHoc");

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiTaiLieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiLieu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex(new[] { "MaGiaoVien" }, "IX_TaiLieu_MaGiaoVien");

                    b.HasIndex(new[] { "MaLop" }, "IX_TaiLieu_MaLop");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TestDauVao", b =>
                {
                    b.Property<int>("MaTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTest"));

                    b.Property<decimal?>("DiemDoc")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemNghe")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemNguPhap")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DiemViet")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("HocVienMaHocVien")
                        .HasColumnType("int");

                    b.Property<string>("KetQua")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KhoaHocDeXuat")
                        .HasColumnType("int");

                    b.Property<string>("LoTrinhHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTest")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongDiem")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTest");

                    b.HasIndex("HocVienMaHocVien");

                    b.HasIndex(new[] { "KhoaHocDeXuat" }, "IX_TestDauVao_KhoaHocDeXuat");

                    b.HasIndex(new[] { "MaHocVien" }, "IX_TestDauVao_MaHocVien");

                    b.ToTable("TestDauVao");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.BaoCao", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "NguoiLapNavigation")
                        .WithMany("BaoCaos")
                        .HasForeignKey("NguoiLap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiLapNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemDanh", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigationMaNguoiDungNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaHocVienNavigationMaNguoiDung");

                    b.HasOne("EnlightEnglishCenter.Models.LichHoc", "MaLichNavigationMaLichNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaLichNavigationMaLich");

                    b.Navigation("MaHocVienNavigationMaNguoiDungNavigation");

                    b.Navigation("MaLichNavigationMaLichNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemSo", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DkHocVienLopHoc", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("DkHocVienLopHocs")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("DkHocVienLopHocs")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.GiaoVien", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "NguoiDung")
                        .WithMany("GiaoViens")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.HocPhi", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("HocPhis")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("HocPhis")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichHoc", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGiaoVien");

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "LopHoc")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaLop");

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichSuTruyCap", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LichSuTruyCaps")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichThi", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("LichThis")
                        .HasForeignKey("MaLop");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LopHoc", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.GiaoVien", "MaGiaoVienNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaGiaoVien");

                    b.HasOne("EnlightEnglishCenter.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoaHoc");

                    b.Navigation("MaGiaoVienNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LuongGiaoVien", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.GiaoVien", "MaGiaoVienNavigation")
                        .WithMany("LuongGiaoViens")
                        .HasForeignKey("MaGiaoVien");

                    b.Navigation("MaGiaoVienNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NguoiDung", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NhanVienLeTan", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.PhanCongGiangDay", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGiaoVien");

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaLop");

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.PhongDaoTao", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TaiLieu", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.GiaoVien", "MaGiaoVienNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaGiaoVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaGiaoVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TestDauVao", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.HocVien", null)
                        .WithMany("TestDauVaos")
                        .HasForeignKey("HocVienMaHocVien");

                    b.HasOne("EnlightEnglishCenter.Models.KhoaHoc", "KhoaHocDeXuatNavigation")
                        .WithMany("TestDauVaos")
                        .HasForeignKey("KhoaHocDeXuat");

                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "HocVien")
                        .WithMany("TestDauVaos")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHocDeXuatNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.GiaoVien", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("LuongGiaoViens");

                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.HocVien", b =>
                {
                    b.Navigation("TestDauVaos");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("TestDauVaos");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichHoc", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LopHoc", b =>
                {
                    b.Navigation("DiemSos");

                    b.Navigation("DkHocVienLopHocs");

                    b.Navigation("HocPhis");

                    b.Navigation("LichHocs");

                    b.Navigation("LichThis");

                    b.Navigation("PhanCongGiangDays");

                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NguoiDung", b =>
                {
                    b.Navigation("BaoCaos");

                    b.Navigation("DiemDanhs");

                    b.Navigation("DiemSos");

                    b.Navigation("DkHocVienLopHocs");

                    b.Navigation("GiaoViens");

                    b.Navigation("HocPhis");

                    b.Navigation("LichSuTruyCaps");

                    b.Navigation("TestDauVaos");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
