// <auto-generated />
using System;
using EnlightEnglishCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnlightEnglishCenter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022154617_UpdateTrungTamSchema")]
    partial class UpdateTrungTamSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnlightEnglishCenter.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("LoaiBaoCao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiLap")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("NguoiLap");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DangKyTuVan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DangKyTuVan");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemDanh", b =>
                {
                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<int?>("MaHocVienNavigationMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaLichNavigationMaLich")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHocVien", "MaLich");

                    b.HasIndex("MaHocVienNavigationMaNguoiDung");

                    b.HasIndex("MaLichNavigationMaLich");

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemSo", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLop");

                    b.ToTable("DiemSo");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DkHocVienLopHoc", b =>
                {
                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHocVien", "MaLop");

                    b.HasIndex("MaLop");

                    b.ToTable("DK_HocVien_LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.HocPhi", b =>
                {
                    b.Property<int>("MaHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocPhi"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDongCuoi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienDaDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienPhaiDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHocPhi");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLop");

                    b.ToTable("HocPhi");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("CapDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuanDauRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HocPhi")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("LoTrinhHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichHoc", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayHoc")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaLop");

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichSuTruyCap", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("DiaChiIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuTruyCap");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichThi", b =>
                {
                    b.Property<int>("MaThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThi"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("GioThi")
                        .HasColumnType("time");

                    b.Property<string>("LoaiThi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayThi")
                        .HasColumnType("date");

                    b.HasKey("MaThi");

                    b.HasIndex("MaLop");

                    b.ToTable("LichThi");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int?>("SiSoHienTai")
                        .HasColumnType("int");

                    b.Property<int?>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGiaoVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LuongGiaoVien", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuong"));

                    b.Property<decimal?>("LuongMoiBuoi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int?>("SoBuoiDay")
                        .HasColumnType("int");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongLuong")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)");

                    b.HasKey("MaLuong");

                    b.HasIndex("MaGiaoVien");

                    b.ToTable("LuongGiaoVien");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("KhoaDenNgay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("SoLanSaiMatKhau")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiLieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiLieu");

                    b.HasIndex("MaGiaoVien");

                    b.HasIndex("MaLop");

                    b.ToTable("TaiLieu");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TestDauVao", b =>
                {
                    b.Property<int>("MaTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTest"));

                    b.Property<decimal?>("DiemDoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemNghe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemNguPhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemViet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KhoaHocDeXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoTrinhHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTest")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongDiem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTest");

                    b.HasIndex("MaHocVien");

                    b.ToTable("TestDauVao");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.BaoCao", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "NguoiLapNavigation")
                        .WithMany("BaoCaos")
                        .HasForeignKey("NguoiLap")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiLapNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemDanh", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaHocVienNavigationMaNguoiDung");

                    b.HasOne("EnlightEnglishCenter.Models.LichHoc", "MaLichNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaLichNavigationMaLich");

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLichNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DiemSo", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.DkHocVienLopHoc", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "HocVien")
                        .WithMany()
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.HocPhi", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaHocVienNavigation")
                        .WithMany("HocPhis")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("HocPhis")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichHoc", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("LichHocs")
                        .HasForeignKey("MaLop");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichSuTruyCap", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LichSuTruyCaps")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichThi", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("LichThis")
                        .HasForeignKey("MaLop");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LopHoc", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaGiaoVienNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaGiaoVien");

                    b.HasOne("EnlightEnglishCenter.Models.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoaHoc");

                    b.Navigation("MaGiaoVienNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LuongGiaoVien", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaGiaoVienNavigation")
                        .WithMany("LuongGiaoViens")
                        .HasForeignKey("MaGiaoVien");

                    b.Navigation("MaGiaoVienNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NguoiDung", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TaiLieu", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "MaGiaoVienNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaGiaoVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnlightEnglishCenter.Models.LopHoc", "MaLopNavigation")
                        .WithMany("TaiLieus")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaGiaoVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.TestDauVao", b =>
                {
                    b.HasOne("EnlightEnglishCenter.Models.NguoiDung", "HocVien")
                        .WithMany("TestDauVaos")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.KhoaHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LichHoc", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.LopHoc", b =>
                {
                    b.Navigation("DiemSos");

                    b.Navigation("HocPhis");

                    b.Navigation("LichHocs");

                    b.Navigation("LichThis");

                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.NguoiDung", b =>
                {
                    b.Navigation("BaoCaos");

                    b.Navigation("DiemDanhs");

                    b.Navigation("DiemSos");

                    b.Navigation("HocPhis");

                    b.Navigation("LichSuTruyCaps");

                    b.Navigation("LopHocs");

                    b.Navigation("LuongGiaoViens");

                    b.Navigation("TaiLieus");

                    b.Navigation("TestDauVaos");
                });

            modelBuilder.Entity("EnlightEnglishCenter.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
